name: Build and Deploy

on:
  push:
    branches:
      - dev
      - ci-cd

env:
  DOCKER_HUB_IMAGE: ${{ secrets.DOCKER_HUB_USERNAME }}/builder-spx-gui:latest

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - uses: actions/checkout@v4

      - name: Setup Go 1.21.x
        uses: actions/setup-go@v4
        with:
          # Semantic version range syntax or exact version of Go
          go-version: '1.21.x'

      - name: Build WASM
        working-directory: spx-gui
        run: ./build-wasm.sh

      - name: Enable Corepack
        run: corepack enable

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: spx-gui/package-lock.json

      - name: Load additional environment variables
        run: echo '${{ secrets.DOTENV_FILE }}' > spx-gui/.env.local

      - name: Install modules
        working-directory: spx-gui
        run: npm install

      - name: Build project
        working-directory: spx-gui
        run: npm run build

      - name: Build and push Docker image
        working-directory: spx-gui
        run: |
          docker build -t $DOCKER_HUB_IMAGE .
          docker push $DOCKER_HUB_IMAGE
